<a href="https://colab.research.google.com/github/VishnuCodes96/capstone_projects/blob/main/capstone_project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing all the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# importing the data
states = pd.read_csv('final_state-wise_renewable_energy_2025-26.csv')

In [3]:
# Basic Checks
states.head()

,States,Capacity_By_Location,Capacity_Including_Allocated_Shares,Rooftop_Solar_Capacity,Generation,Peak_Demand,Hydro,Nuclear,Other_RES,Thermal,Population
0,Andhra Pradesh,31646.31,30419.54,774.5,98620.87,14011,3353.60,127.27,12690.11,14248.56,535.24
1,Telangana,19773.08,21852.44,695.9,73319.98,18548,2479.93,148.73,5524.98,13698.80,384.54
2,Tamil Nadu,47637.05,47618.83,1532.3,132210.74,20211,2203.20,1448.00,26954.38,17013.25,773.17
3,Haryana,8773.31,14845.56,1188.3,28032.91,13998,2490.83,123.04,3011.72,9219.97,309.36
4,Punjab,9119.93,14764.16,581.2,39557.58,17171,3827.44,229.09,2343.63,8364.00,311.22

In [4]:
states.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 11 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   States                               18 non-null     object
 1   Capacity_By_Location                 18 non-null     float64
 2   Capacity_Including_Allocated_Shares  18 non-null     float64
 3   Rooftop_Solar_Capacity               18 non-null     float64
 4   Generation                           18 non-null     float64
 5   Peak_Demand                          18 non-null     int64
 6   Hydro                                18 non-null     float64
 7   Nuclear                              11 non-null     float64
 8   Other_RES                            18 non-null     float64
 9   Thermal                              18 non-null     float64
 10  Population                           18 non-null     float64
dtypes: float64(9), int64(1), object(1)
memory usage: 1.7+ KB

In [5]:
states.describe().T

,count,mean,std,min,25%,50%,75%,max
Capacity_By_Location,18.0,23371.534444,22717.115333,83.49,7833.0200,14600.010,32926.0575,71690.64
Capacity_Including_Allocated_Shares,18.0,22704.162778,23230.257240,290.98,5083.1200,14804.860,30198.4750,70945.39
Rooftop_Solar_Capacity,18.0,1178.706111,1918.273642,6.68,110.2500,462.700,1114.5000,6881.80
Generation,18.0,80464.786111,61581.223729,65.25,30914.0775,75780.530,136208.1875,172616.73
Peak_Demand,18.0,12474.055556,9454.793677,228.00,3810.0000,13553.000,19098.5000,32419.00
Hydro,18.0,1654.768333,1319.286753,5.00,400.4750,1825.185,2488.1050,3827.44
Nuclear,11.0,514.150000,492.017539,41.68,131.4200,229.090,920.8150,1448.00
Other_RES,18.0,10392.831667,15617.522034,22.98,622.0325,2273.595,12004.4925,46608.04
Thermal,18.0,10342.360000,7954.774506,83.87,4059.0775,9209.655,14607.6525,27838.97
Population,18.0,553.236667,397.338755,15.90,309.8250,436.590,814.0675,1304.29